# ----------------------------------------------------------------------------------------------------------------
# Y90 PET MC Simulation - Philips Vereos PET/CT Scanner with Patient-Specific Phantom and PET Image as Source Map
# ----------------------------------------------------------------------------------------------------------------

#=====================================================
# VERBOSITY
#=====================================================

/control/execute mac/verbose.mac

#=====================================================
# VISUALIZATION
#=====================================================

/vis/disable
#/control/execute mac/visu.mac # activate for visualization, need to comment the /vis/disable

#=====================================================
# PET SCANNER GEOMETRY
#=====================================================

/gate/geometry/setMaterialDatabase data/GateMaterials.db

/control/execute mac/pet_geometry.mac

/control/execute mac/table_geometry.mac

#=====================================================
# DIGITIZER : DETECTOR ELECTRONIC RESPONSE
#=====================================================

/control/execute mac/digitizer.mac

#=====================================================
# VOXELIZED GEOMETRY - PATIENT-SPECIFIC PHANTOM
#=====================================================

# Generate materials/composition and density from Hounsfield units present in CT Image 
/gate/HounsfieldMaterialGenerator/SetMaterialTable data/GEMINIMaterialsTable.txt
/gate/HounsfieldMaterialGenerator/SetDensityTable  data/GEMINIDensitiesTable.txt
/gate/HounsfieldMaterialGenerator/SetDensityTolerance               0.01 g/cm3
/gate/HounsfieldMaterialGenerator/SetOutputMaterialDatabaseFilename data/patient-HUmaterials.db
/gate/HounsfieldMaterialGenerator/SetOutputHUMaterialFilename       data/patient-HU2mat.txt
/gate/HounsfieldMaterialGenerator/Generate

# Definition of the patient phantom and selection of algorithm
/gate/world/daughters/name                      phantom_patient
/gate/world/daughters/insert                    ImageNestedParametrisedVolume
/gate/phantom_patient/geometry/setImage         images/ct_pet_y90.mhd

# Output files that read the description of materials Housefield units from CT Image 
/gate/geometry/setMaterialDatabase                      data/patient-HUmaterials.db
/gate/phantom_patient/geometry/setHUToMaterialFile      data/patient-HU2mat.txt

# Voxelized Phantom position at center of the world
/gate/phantom_patient/placement/setTranslation 0 0 0 mm

# Flip the patient phantom so that it's correctly placed according to original offset
/gate/phantom_patient/placement/setRotationAxis 0 0 1

/gate/phantom_patient/vis/forceWireframe
/gate/phantom_patient/vis/setVisible   1

/gate/phantom_patient/attachPhantomSD

#=====================================================
# PHYSICS
#=====================================================

# Geant4 physics list selected
/gate/physics/addPhysicsList emstandard_opt3

# Cuts of 10 keV for all geometry simulation because it helps reduce simulation time

# Cuts in world
/gate/physics/Gamma/SetCutInRegion     world  5.0 mm
/gate/physics/Electron/SetCutInRegion  world  5.0 mm
/gate/physics/Positron/SetCutInRegion  world  5.0 mm

# Cuts in patient-specific phantom - moderate cuts
/gate/physics/Gamma/SetCutInRegion      phantom_patient  0.6 mm
/gate/physics/Electron/SetCutInRegion   phantom_patient  0.01 mm
/gate/physics/Positron/SetCutInRegion   phantom_patient  0.01 mm

# Patient bed — to reduce scatter and random coincidences
/gate/physics/Gamma/SetCutInRegion     bed          2.0 mm
/gate/physics/Electron/SetCutInRegion  bed          2.0 mm
/gate/physics/Positron/SetCutInRegion  bed          2.0 mm

# LYSO crystal — very fine for energy deposition accuracy
/gate/physics/Gamma/SetCutInRegion     crystal      0.1 mm
/gate/physics/Electron/SetCutInRegion  crystal      0.01 mm
/gate/physics/Positron/SetCutInRegion  crystal      0.01 mm

# Minimum kinetic energy - Stops a particle that has less energy than the pre-defined minimum kinetic energy so the energy is deposited locally  
/gate/physics/SetMinKineticEnergyInRegion              phantom_patient 10. keV
/gate/physics/ActivateSpecialCuts                      e-
/gate/physics/SetMinKineticEnergyInRegion              phantom_patient 10. keV
/gate/physics/ActivateSpecialCuts                      e+

/gate/physics/processes/PhotoElectric/setAugerElectron true
/gate/physics/processes/PhotoElectric/setDeltaRayCut  10. keV 
/gate/physics/processes/PhotoElectric/setXRayCut      10. keV

# Initiate Physics 
/gate/physics/processList Enabled

#=====================================================
# ACTORS FOR STATISTICS - INFO ABOUT SIMULATION
#=====================================================

/gate/actor/addActor               SimulationStatisticActor stat
/gate/actor/stat/save              Output_PET_Simulation/stats_PET.txt
/gate/actor/stat/saveEveryNSeconds 60

#=====================================================
# ACTORS FOR ATTENUATION CORRECTION MAP
#=====================================================

/gate/actor/addActor MuMapActor getMuMap
/gate/actor/getMuMap/attachTo phantom_patient
/gate/actor/getMuMap/save Output_PET_Simulation/Attenuation_Image.mhd
/gate/actor/getMuMap/setPosition 0 0 0 mm
/gate/actor/getMuMap/setVoxelSize 2.21 2.21 2.21 mm
/gate/actor/getMuMap/setResolution 125 122 93
/gate/actor/getMuMap/setEnergy 511 keV

#=====================================================
# OUTPUTS
#=====================================================

# Define a PET ROOT list-mode file output

/gate/output/root/enable
/gate/output/root/setFileName             Output_PET_Simulation/PETVereoslistmode_Y90

/gate/output/root/setRootHitFlag          0
/gate/output/root/setRootSinglesFlag      0
/gate/output/root/setRootCoincidencesFlag 1
/gate/output/root/setRootDelayFlag        1
/gate/output/root/setRootNtupleFlag       0

# Summary events output 
/gate/output/summary/enable
/gate/output/summary/setFileName   Output_PET_Simulation/events_summaryPETVereos_Y90.txt
/gate/output/summary/addCollection Singles
/gate/output/summary/addCollection Coincidences
/gate/output/summary/addCollection Delay

#=====================================================
# INITIALISATION OF SIMULATION
#=====================================================

/gate/run/initialize

/gate/physics/processList Initialized

/gate/physics/displayCuts

#=====================================================
# VOXELIZED SOURCE
#=====================================================

/gate/source/addSource Y90Source voxel
/gate/source/Y90Source/reader/insert	image

# Linear translator: this scales all image values directly into activities
/gate/source/Y90Source/imageReader/translator/insert linear
# PET image is expressed in MBq
/gate/source/Y90Source/imageReader/linearTranslator/setScale 1 MBq
/gate/source/Y90Source/imageReader/readFile images/pet_y90_masked.mhd

/gate/source/Y90Source/imageReader/verbose 1

# Position of the PET Image aligned with patient phantom
# half of the volume’s size in the negative direction
# dimensions : 125 122 93
# voxel size : 2.2100000381469727 2.2100000381469727 2.2100000381469727
/gate/source/Y90Source/setPosition -138.125 -134.810 -102.765 mm

# Attach to patient phantom
/gate/source/Y90Source/attachTo phantom_patient

###########################################################################################
### Y90 Positron Spectrum
### Energies of the positrons from Y90 decay
### From article https://www.sciencedirect.com/science/article/pii/S0969804319303689#fig1
###########################################################################################

# Positron particle
/gate/source/Y90Source/gps/particle e+

# Half life is 64.2 hours of Y90
/gate/source/Y90Source/setForcedHalfLife 230760 s
/gate/source/Y90Source/setForcedUnstableFlag  true

# Y90 positrons energy spectrum file
/gate/source/Y90Source/gps/energytype UserSpectrum
/gate/source/Y90Source/gps/setSpectrumFile data/Y90positronSpectrum.txt

# This confines the generation of particles to a cube with a size of the image voxels of 2.21 mm 
# The spatial distribution of primary particles generation within this volume is uniform
/gate/source/Y90Source/gps/type     Volume
/gate/source/Y90Source/gps/shape    Para
/gate/source/Y90Source/gps/pos/halfx  1.105 mm
/gate/source/Y90Source/gps/pos/halfy  1.105 mm
/gate/source/Y90Source/gps/pos/halfz  1.105 mm
/gate/source/Y90Source/gps/ang/type iso
/gate/source/Y90Source/gps/centre 0 0 0 mm

/gate/source/Y90Source/dump 1
/gate/source/list

#====================================================
# RANDOM ENGINE AND SEED
#====================================================

# JamesRandom Ranlux64 MersenneTwister Options
/gate/random/setEngineName MersenneTwister
/gate/random/setEngineSeed auto
/gate/random/verbose 1

#=====================================================
# ACQUISITION SETTINGS   
#=====================================================

# Limit on the total number of primary particles to reduce simulation computational time
/gate/application/setTotalNumberOfPrimaries 7e9

#/gate/application/setTotalNumberOfPrimaries 10  # activate only for visualization

# Set PET acquisition times
/gate/application/setTimeSlice 30 s
/gate/application/setTimeStart 0 s
/gate/application/setTimeStop  120 s

#=====================================================
# RUN SIMULATION
#=====================================================

/gate/application/startDAQ
