# -----------------------------------------------------------------------------------------------------------------
#  Y90 MC Dosimetry Simulation with Patient-Specific Phantom designed on 3D Slicer and PET Image as as Source Map  
# -----------------------------------------------------------------------------------------------------------------

#=====================================================
# VERBOSITY
#=====================================================

/control/execute mac/verbose.mac

#=====================================================
# VISUALIZATION
#=====================================================

/vis/disable
#/control/execute mac/visu.mac # activate for visualization, need to comment the /vis/disable

#=====================================================
# GEOMETRY
#=====================================================

# Upload of GATE Materials Database file
/gate/geometry/setMaterialDatabase data/GateMaterials.db

# Simulation World
/gate/world/geometry/setXLength  50 cm
/gate/world/geometry/setYLength  50 cm
/gate/world/geometry/setZLength  50 cm
/gate/world/setMaterial Air
/gate/world/vis/forceWireframe
/gate/world/vis/setVisible 1
/gate/world/vis/setColor blue

#=====================================================
# VOXELIZED GEOMETRY - PATIENT-SPECIFIC PHANTOM
#=====================================================

# Definition of the patient phantom and selection of algorithm
/gate/world/daughters/name                      phantom_patient
/gate/world/daughters/insert                    ImageNestedParametrisedVolume
/gate/phantom_patient/geometry/setImage         images/ct_pet_y90_3DSlicerPhantom.mhd

# File which converts voxel values in the image to materials in GateMaterials.dB file
/gate/phantom_patient/geometry/setRangeToMaterialFile data/GateRangeTranslator.dat

# Voxelized Phantom position at center of the world
/gate/phantom_patient/placement/setTranslation 0 0 0 mm

# Flip the patient phantom so that it's correctly placed according to original offset
/gate/phantom_patient/placement/setRotationAxis 0 0 1

/gate/phantom_patient/vis/forceWireframe
/gate/phantom_patient/vis/setVisible   1

#=====================================================
# PHYSICS
#=====================================================

# Geant4 physics list selected
/gate/physics/addPhysicsList emstandard_opt3

# Cuts in world
/gate/physics/Gamma/SetCutInRegion      world  10 mm
/gate/physics/Electron/SetCutInRegion   world  10 mm
/gate/physics/Positron/SetCutInRegion   world  10 mm

# Cuts of 10 keV for all geometry simulation because it helps reduce simulation time

# Cuts in patient-specific phantom
/gate/physics/Gamma/SetCutInRegion      phantom_patient  2 mm
/gate/physics/Electron/SetCutInRegion   phantom_patient  20 mm
/gate/physics/Positron/SetCutInRegion   phantom_patient  20 mm

/gate/physics/processes/PhotoElectric/setDeltaRayCut     10.0 keV
/gate/physics/processes/PhotoElectric/setXRayCut         10.0 keV

# Minimum kinetic energy - Stops a particle that has less energy than the pre-defined minimum kinetic energy so the energy is deposited locally 
/gate/physics/SetMinKineticEnergyInRegion              phantom_patient 20. keV
/gate/physics/ActivateSpecialCuts                      e-
/gate/physics/SetMinKineticEnergyInRegion              phantom_patient 10. keV
/gate/physics/ActivateSpecialCuts                      gamma

# Particle maximum step size for Y90 - value from article "A dose point kernel database using GATE Monte Carlo simulation toolkit for nuclear medicine applications: Comparison with other Monte Carlo codes"
/gate/physics/SetMaxStepSizeInRegion phantom_patient 0.11 mm
/gate/physics/ActivateStepLimiter e-

/gate/physics/processes/PhotoElectric/setAugerElectron true
/gate/physics/processes/PhotoElectric/setDeltaRayCut  10. keV 
/gate/physics/processes/PhotoElectric/setXRayCut      10. keV

# Initiate Physics 
/gate/physics/processList Enabled

#=====================================================
# ACTOR DOSE - OUTPUT FILES FROM DOSIMETRY
#=====================================================

# Set aliasing for size and resolution of dose actor
# Needs to match size of CT and PET images
# x = 125 * 2.2100000381469727 mm
# y = 122 * 2.2100000381469727 mm
# z = 93 * 2.2100000381469727 mm

# DOSE ACTOR ==============================
# builds 3D images of:
#   - the energy deposited (edep in MeV)
#   - dose deposited (Gy)
#   - the number of hits in a volume

/gate/actor/addActor                     DoseActor  dose3D
/gate/actor/dose3D/attachTo    	         phantom_patient
/gate/actor/dose3D/stepHitType           random
/gate/actor/dose3D/setPosition           0 0 0 mm
/gate/actor/dose3D/setVoxelSize          2.21 2.21 2.21 mm
/gate/actor/dose3D/setResolution         125 122 93
/gate/actor/dose3D/setDoseAlgorithm      MassWeighting
/gate/actor/dose3D/enableEdep            true
/gate/actor/dose3D/enableUncertaintyEdep true
/gate/actor/dose3D/enableDose            true
/gate/actor/dose3D/enableUncertaintyDose true
/gate/actor/dose3D/enableSquaredDose     true
/gate/actor/dose3D/enableNumberOfHits    true
/gate/actor/dose3D/save                  OUTPUT_Dosimetry_Simulation_3DSlicerPhantom/DOSE_Y90.mhd
/gate/actor/dose3D/saveEveryNSeconds     60

#=====================================================
#  ACTOR FOR Y90 SPECTRUM - EnergySpectrumActor
#=====================================================

# This actor builds one file containing the electron energy spectrum histograms. Ideally one specifies the lower (Emin) and upper (Emax) boundary of the histogram and the resolution/number of bins

/gate/actor/addActor EnergySpectrumActor electron_actor
/gate/actor/electron_actor/attachTo phantom_patient
/gate/actor/electron_actor/addFilter    particleFilter
/gate/actor/electron_actor/particleFilter/addParticle  e-
/gate/actor/electron_actor/save  OUTPUT_Dosimetry_Simulation_3DSlicerPhantom/Y90_electronspectrum.root
/gate/actor/electron_actor/energySpectrum/setEmin 0 eV
/gate/actor/electron_actor/energySpectrum/setEmax 2.28 MeV
/gate/actor/electron_actor/energySpectrum/setNumberOfBins 100

#=====================================================
# ACTORS FOR STATISTICS - INFO ABOUT SIMULATION
#=====================================================

/gate/actor/addActor               SimulationStatisticActor stat
/gate/actor/stat/save              OUTPUT_Dosimetry_Simulation_3DSlicerPhantom/stats_dosimetryY90.txt
/gate/actor/stat/saveEveryNSeconds 60

#=====================================================
# INITIALISATION OF SIMULATION
#=====================================================

/gate/run/initialize

/gate/physics/processList Initialized

/gate/physics/displayCuts

#=====================================================
#  VOXELIZED SOURCE
#=====================================================

/gate/source/addSource Y90Source voxel
/gate/source/Y90Source/reader/insert	image

# Linear translator: this scales all image values directly into activities
/gate/source/Y90Source/imageReader/translator/insert linear
# PET image is expressed in MBq
/gate/source/Y90Source/imageReader/linearTranslator/setScale 1 MBq
/gate/source/Y90Source/imageReader/readFile images/pet_y90_masked.mhd

/gate/source/Y90Source/imageReader/verbose 1

# Position of the PET Image aligned with patient phantom
# half of the volume’s size in the negative direction
# dimensions : 125 122 93
# voxel size : 2.2100000381469727 2.2100000381469727 2.2100000381469727
/gate/source/Y90Source/setPosition -138.125 -134.810 -102.765 mm

# Attach to patient phantom
/gate/source/Y90Source/attachTo phantom_patient

#####################################################################################
### Y90 Radioembolization Therapy 
### Energies of the electrons from Y90 - beta^- spectrum
### Nuclear data from DECDATA dasabase software available through ICRP Publication 107
### https://www.icrp.org/publication.asp?id=ICRP%20Publication%20107
#####################################################################################

# Electron particle
/gate/source/Y90Source/gps/particle e-

# Half life is 64.2 hours of Y90
/gate/source/Y90Source/setForcedHalfLife 230760 s
/gate/source/Y90Source/setForcedUnstableFlag  true

# Y90 Beta - energies spectrum file
/gate/source/Y90Source/gps/energytype UserSpectrum
/gate/source/Y90Source/gps/setSpectrumFile data/Y90betaspectrum.txt

# This confines the generation of particles to a cube with a size of the image voxels of 2.21 mm 
# The spatial distribution of primary particles generation within this volume is uniform
/gate/source/Y90Source/gps/type     Volume
/gate/source/Y90Source/gps/shape    Para
/gate/source/Y90Source/gps/pos/halfx  1.105 mm
/gate/source/Y90Source/gps/pos/halfy  1.105 mm
/gate/source/Y90Source/gps/pos/halfz  1.105 mm
/gate/source/Y90Source/gps/ang/type iso
/gate/source/Y90Source/gps/centre 0 0 0 mm

/gate/source/Y90Source/dump 1
/gate/source/list

#====================================================
# RANDOM ENGINE AND SEED
#====================================================

# JamesRandom Ranlux64 MersenneTwister
/gate/random/setEngineName MersenneTwister
/gate/random/setEngineSeed auto
/gate/random/verbose 1

#=====================================================
# ACQUISITION SETTINGS   
#=====================================================

# To get the total number of primaries, we use A = decay constant * N
# Usually to ensure a standard deviation / uncertainty of 1 % or less, simulation should be repeated 3 times and sum results 
# or find the best total number of primaries that gives the needed uncertainty

/gate/application/setTotalNumberOfPrimaries 1.18e8

#/gate/application/setTotalNumberOfPrimaries 100  # activate only for visualization

#=====================================================
# RUN SIMULATION
#=====================================================

/gate/application/startDAQ
