#==============================================================================
# DEFINING THE PHILIPS VEREOS DIGITAL DPC PET/CT SCANNER GEOMETRY COMPONENTS
#==============================================================================

# Detector crystal inner diameter = 764.0 mm
# Detector crystal outer diameter = 802.0 mm
# Axial FOV = 164 mm

# MOTHER VOLUME
/gate/world/geometry/setXLength 150. cm
/gate/world/geometry/setYLength 150. cm
/gate/world/geometry/setZLength 150. cm
/gate/world/setMaterial G4_AIR
/gate/world/vis/setVisible 0
/gate/world/vis/setColor white
/gate/world/vis/forceWireframe

# PET CYLINDRICAL STRUCTURE
/gate/world/daughters/name cylindricalPET
/gate/world/daughters/insert cylinder
/gate/cylindricalPET/placement/setTranslation 0.0 0.0 0.0 cm
/gate/cylindricalPET/setMaterial G4_AIR
/gate/cylindricalPET/geometry/setRmax  500.0 mm
/gate/cylindricalPET/geometry/setRmin  360.0 mm 
/gate/cylindricalPET/geometry/setHeight 164.0 mm
/gate/cylindricalPET/vis/forceWireframe
/gate/cylindricalPET/vis/setColor grey
/gate/cylindricalPET/vis/setVisible 1

# CONSTRUCTION OF PET DETECTORS

# ------------------------------------------
# 18 modules
#   of 4x5 stack
#       of 4x4 die
#           of 2x2 crystal
# ------------------------------------------

# MODULE (each module has 4x5 blocks named stacks) - Level 1
/gate/cylindricalPET/daughters/name module
/gate/cylindricalPET/daughters/insert box
/gate/module/placement/setTranslation 391.5 0 0 mm
/gate/module/geometry/setXLength 19 mm
/gate/module/geometry/setYLength 131.4 mm 
/gate/module/geometry/setZLength 164.0 mm
/gate/module/setMaterial ABS
/gate/module/vis/setColor blue
/gate/module/vis/forceWireframe
/gate/module/vis/setVisible 1

# STACK - (each stack has 4x4 die) - Level 2
/gate/module/daughters/name stack
/gate/module/daughters/insert box
/gate/stack/placement/setTranslation 0.0 0.0 0.0 mm
/gate/stack/geometry/setXLength 19 mm
/gate/stack/geometry/setYLength 32.6 mm
/gate/stack/geometry/setZLength 32.6 mm
/gate/stack/setMaterial G4_AIR
/gate/stack/vis/setColor green
/gate/stack/vis/setVisible 1
/gate/stack/vis/forceWireframe

# DIE PHOTODECTECTOR -  (each die has 2x2 LYSO scintillator crystals) - Level 3
/gate/stack/daughters/name die
/gate/stack/daughters/insert box
/gate/die/placement/setTranslation 0.0 0.0 0.0 mm
/gate/die/geometry/setXLength 19 mm
/gate/die/geometry/setYLength 8.0 mm
/gate/die/geometry/setZLength 8.0 mm
/gate/die/setMaterial G4_AIR
/gate/die/vis/setColor white
/gate/die/vis/setVisible 1
/gate/die/vis/forceWireframe

# LYSO SCINTILLATOR CRYSTAL - Level 4
/gate/die/daughters/name crystal
/gate/die/daughters/insert box
/gate/crystal/placement/setTranslation 0.0 0.0 0.0 mm
/gate/crystal/geometry/setXLength 19 mm
/gate/crystal/geometry/setYLength 4.0 mm
/gate/crystal/geometry/setZLength 4.0 mm
/gate/crystal/setMaterial LYSO
/gate/crystal/vis/setColor red
/gate/crystal/vis/forceSolid
/gate/crystal/vis/forceWireframe
/gate/crystal/vis/setVisible 1

# ------------------------------------------
# PHOTODETECTOR HOUSING
# ------------------------------------------

# SiPMs HOUSING
/gate/cylindricalPET/daughters/name housing
/gate/cylindricalPET/daughters/insert box
/gate/housing/placement/setTranslation 408 0 0 mm
/gate/housing/geometry/setXLength 1 mm
/gate/housing/geometry/setYLength 131.0 mm 
/gate/housing/geometry/setZLength 164.0 mm
/gate/housing/setMaterial G4_AIR
/gate/housing/vis/setColor yellow
/gate/housing/vis/forceSolid
/gate/housing/vis/forceWireframe
/gate/housing/vis/setVisible 1

# SiPMs UNITS
/gate/housing/daughters/name sipms
/gate/housing/daughters/insert box
/gate/sipms/placement/setTranslation 0.0 0.0 0.0 mm
/gate/sipms/geometry/setXLength 1 mm
/gate/sipms/geometry/setYLength 32.6 mm
/gate/sipms/geometry/setZLength 32.6 mm
/gate/sipms/setMaterial G4_AIR
/gate/sipms/vis/setColor green
/gate/sipms/vis/setVisible 1
/gate/sipms/vis/forceWireframe


# BACK COMPARTMENTS
/gate/cylindricalPET/daughters/name coolingplate
/gate/cylindricalPET/daughters/insert box
/gate/coolingplate/placement/setTranslation 430.0 0 0 mm
/gate/coolingplate/geometry/setXLength 30 mm
/gate/coolingplate/geometry/setYLength 130.2 mm
/gate/coolingplate/geometry/setZLength 164.0 mm
/gate/coolingplate/setMaterial Copper
/gate/coolingplate/vis/setColor blue
/gate/coolingplate/vis/forceSolid
/gate/coolingplate/vis/forceWireframe
/gate/coolingplate/vis/setVisible 1

# BUILDING UP THE SCANNER GEOMETRY

# ------------------------------------------
# Total LYSO Scintillator crystals = 23040
# Per module = 1280 crystals
# Per stack = 64
# Per die = 4
# ------------------------------------------

# REPEAT LYSO SCINTILLATOR CRYSTAL TO GET A 2x2 SiPM (Die) - Level 4
/gate/crystal/repeaters/insert cubicArray
/gate/crystal/cubicArray/setRepeatNumberX 1
/gate/crystal/cubicArray/setRepeatNumberY 2
/gate/crystal/cubicArray/setRepeatNumberZ 2
/gate/crystal/cubicArray/setRepeatVector 19 4.0 4.0 mm  

# REPEAT DIE TO GET A 8x8 ARRAY - Level 3
/gate/die/repeaters/insert cubicArray
/gate/die/cubicArray/setRepeatNumberX 1
/gate/die/cubicArray/setRepeatNumberY 4
/gate/die/cubicArray/setRepeatNumberZ 4
/gate/die/cubicArray/setRepeatVector 19 8.0 8.0 mm 

# REPEAT STACK TO GET A MODULE WITH 4x5 STACKS - Level 2
/gate/stack/repeaters/insert cubicArray
/gate/stack/cubicArray/setRepeatNumberY 4
/gate/stack/cubicArray/setRepeatNumberZ 5
/gate/stack/cubicArray/setRepeatVector 0. 32.85 32.85 mm

# REPEAT MODULE TO GET A RING WITH 18 MODULES - Level 1
/gate/module/repeaters/insert ring
/gate/module/ring/setFirstAngle 190 deg
/gate/module/ring/setRepeatNumber 18

# REPEAT SiPMs WITHIN the HOUSING
/gate/sipms/repeaters/insert cubicArray
/gate/sipms/cubicArray/setRepeatNumberY 4
/gate/sipms/cubicArray/setRepeatNumberZ 5
/gate/sipms/cubicArray/setRepeatVector 0. 32.8 32.8 mm

# REPEAT THE HOUSING
/gate/housing/repeaters/insert ring
/gate/housing/ring/setFirstAngle 190 deg
/gate/housing/ring/setRepeatNumber 18

/gate/coolingplate/repeaters/insert ring
/gate/coolingplate/ring/setFirstAngle 190 deg
/gate/coolingplate/ring/setRepeatNumber 18

# END SHIELDING 1 - reduces the interferences from activity outside the FOV
/gate/world/daughters/name endshielding1
/gate/world/daughters/insert cylinder
/gate/endshielding1/placement/setTranslation 0.0 0.0 95.0 mm
/gate/endshielding1/geometry/setRmax   410.0 mm
/gate/endshielding1/geometry/setRmin   362.5 mm 
/gate/endshielding1/geometry/setHeight 25.0 mm 
/gate/endshielding1/setMaterial Lead
/gate/endshielding1/vis/setColor yellow
/gate/endshielding1/vis/forceSolid
/gate/endshielding1/vis/forceWireframe
/gate/endshielding1/vis/setVisible 1

# END SHIELDING 2
/gate/world/daughters/name endshielding2
/gate/world/daughters/insert cylinder
/gate/endshielding2/placement/setTranslation 0.0 0.0 -95.0 mm
/gate/endshielding2/geometry/setRmax   410.0 mm
/gate/endshielding2/geometry/setRmin   362.5 mm 
/gate/endshielding2/geometry/setHeight 25.0 mm 
/gate/endshielding2/setMaterial Lead
/gate/endshielding2/vis/setColor yellow
/gate/endshielding2/vis/forceSolid
/gate/endshielding2/vis/forceWireframe
/gate/endshielding2/vis/setVisible 1

# Outer cover Lexan layer - This is the inner plastic housing surrounding the FOV which takes into account scatter radiation and attenuation effects in surrounding materials
/gate/world/daughters/name cover
/gate/world/daughters/insert cylinder
/gate/cover/placement/setTranslation 0.0 0.0 0.0 cm
/gate/cover/geometry/setRmax   355.5 mm
/gate/cover/geometry/setRmin   354.0 mm
/gate/cover/geometry/setHeight 392.0 mm 
/gate/cover/setMaterial Lexan
/gate/cover/vis/forceSolid
/gate/cover/vis/forceWireframe
/gate/cover/vis/setColor white
/gate/cover/vis/setVisible 1

# ATTACH SYSTEM 
# Depth of the readout segmentation
# Depth 1 is the rsector which for the Alpha is the module
# Depth 2 is the module which for the Alpha is the stack
# Depth 3 is the submodules which for the Alpha is the die
# Depth 4 is the crystal which for the Alpha is the crystal

/gate/systems/cylindricalPET/rsector/attach module
/gate/systems/cylindricalPET/module/attach stack
/gate/systems/cylindricalPET/submodule/attach die
/gate/systems/cylindricalPET/crystal/attach crystal

# ATTACH LAYER SD (sensitive detector)
/gate/crystal/attachCrystalSD

/gate/systems/cylindricalPET/describe
